### ISSUE TITLE
Przypisywanie kandydatom testów

### ISSUE THREAD

**Issue by paluszkiewiczB** [lodz-university-of-technology-masi/Wylosowana#13]
Parent: #3 
Po wybraniu testu, który chcemy udostępnić:
 - pobranie danych o kandydatach, których można przydzielić do danego testu
 - po wybraniu kandydatów i zatwierdzeniu udostępnieniu testu: dopisanie ID do tablicy w polu candidate_ids

**Comment by paluszkiewiczB** [comment]
Duplikat #9 ?

**Comment by goloneczka** [comment]
tak bym powiedzial ze duplikat. Dostarczałbym modulówi "udostepnianie testow" odpowiednie teste i uczestnikow, a on by sam je udostepnial

![Bez tytułu](https://user-images.githubusercontent.com/48791689/68085952-e08ccb00-fe46-11e9-929c-430b61f5048c.png)

wtedy modl "udostepnianie testow"  musiałby tez modyfikowac baze, ewentualnie mi przekazywac jakies parametry do aktualizacji bazy.

Reasumujac musze wspolpracowac z ta funkcjonalnoscia, ale nie jest ona moja 💃
